# Generated by Django 4.2.11 on 2024-03-18 12:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUE', 'В очереди'), ('DIARIZING', 'Диаризация'), ('TRANSCRIBING', 'Транскрипция'), ('TRANSLATING', 'Перевод'), ('PROCESSED', 'Выполнен'), ('FAILED', 'Ошибка')], default='QUEUE', max_length=32, verbose_name='Статус')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('original_file', models.FileField(upload_to='contents/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'wav'))], verbose_name='Оригинальный файл')),
                ('original_language', models.CharField(max_length=32, verbose_name='Оригинальный язык')),
                ('translate_to', models.CharField(max_length=32, verbose_name='Перевод на')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность')),
                ('additional_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительные данные')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контенты',
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=32, verbose_name='Говорящий')),
                ('from_time', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Время начала')),
                ('to_time', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Время конца')),
                ('text', models.TextField(verbose_name='Текст')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='storage.content', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Речь',
                'verbose_name_plural': 'Речи',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.folder', verbose_name='Папка'),
        ),
        migrations.AddField(
            model_name='content',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
