# Generated by Django 4.2.11 on 2024-03-15 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('audio', models.FileField(upload_to='contents/%Y/%m/%d', verbose_name='Аудио')),
                ('status', models.CharField(choices=[('PROCESSING', 'Обрабатывается'), ('PROCESSED', 'Обработан'), ('FAILED', 'Ошибка')], default='PROCESSING', max_length=32, verbose_name='Статус')),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Длительность')),
                ('language', models.CharField(default='en', max_length=8, verbose_name='Язык аудио')),
                ('additional_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительные данные')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контенты',
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=32, verbose_name='Говорящий')),
                ('from_time', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Время начала')),
                ('to_time', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Время конца')),
                ('text', models.TextField(verbose_name='Текст')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='storage.content', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Речь',
                'verbose_name_plural': 'Речи',
            },
        ),
    ]
