# Generated by Django 4.2.11 on 2024-03-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_content_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('QUEUE', 'В очереди'), ('DIARIZING', 'Диаризация'), ('TRANSCRIBING', 'Транскрипция'), ('TRANSLATING', 'Перевод'), ('PROCESSED', 'Выполнен'), ('FAILED', 'Ошибка')], default='QUEUE', max_length=32, verbose_name='Статус'),
        ),
    ]
