# Generated by Django 4.2.11 on 2024-03-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_content_created_at_content_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='audio',
        ),
        migrations.AddField(
            model_name='content',
            name='original_file',
            field=models.FileField(default=1, upload_to='contents/%Y/%m/%d', verbose_name='Оригинальный файл'),
            preserve_default=False,
        ),
    ]
